baseurl = "/"
languageCode = "ru"
title = "Блог Дмитрия Агапова"
author = "Дмитрий Агапов"
# Shown in the side menu
copyright = "&copy; 2017. All rights reserved."
canonifyurls = true
paginate = 10
theme = "blackburn"

[taxonomies]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Новости и Фотографии"
  brand = "Dmitry A."
  googleAnalytics = "UA-96967205-1"
  disqus = "agapovd-ru"
  # CSS name for highlight.js
  # highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  # custom_css = ["css/my.css"]
  # custom_js = ["js/my.js"]

[menu]
  # Shown in the side menu.
  #[[menu.main]]
  #  name = "Home"
  #  pre = "<i class='fa fa-home fa-fw'></i>"
  #  weight = 1
  #  identifier = "home"
  #  url = "/"

  [[menu.main]]
    name = "Мой Блог"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"

  [[menu.main]]
    name = "Репосты"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "repost"
    url = "/repost/"

  #[[menu.main]]
  #  name = "Новости"
  #  pre = "<i class='fa fa-newspaper-o fa-fw'></i>"
  #  weight = 3
  #  identifier = "news"
  #  url = "/news/"

  [[menu.main]]
    name = "Все Разделы"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 4
    url = "/topics/"

  [[menu.main]]
    name = "Тэги"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 5
    url = "/tags/"

  [[menu.main]]
    name = "О Сайте"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 6
    identifier = "about"
    url = "/about/"

  [[menu.main]]
    name = "Нелли Лисица"
    pre = "<i class='fa fa-external-link-square fa-fw'></i>"
    weight = 7
    identifier = "link"
    url = "http://fpsiholog.org"

 # [[menu.main]]
 #  name = "Contact"
 #  pre = "<i class='fa fa-phone fa-fw'></i>"
 #  weight = 7
 #  url = "/contact/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  vk = "dmitri_a"
  twitter = "Agapof"
  # gnusocial = "*" # Specify href (e.g. https://quitter.se/yourusername)
  facebook = "dmitry.petrosyan.58"
  googleplus = "DmitryAgapov"
  # weibo = "*"
  # tumblr = "*"

  # SNS photo/video sharing
  instagram = "dagapof"
  # flickr = "*"
  # pinterest = "*"
  youtube = "DAgapof"
  # vimeo = "*"
  # vine = "*"
  # slideshare = "*"

  # SNS career oriented
  # linkedin = "*"
  # xing = "*"

  # SNS news
  # reddit = "*"
  # hackernews = "*"

  # Techie
  github = "dmitrij-a"
  # bitbucket = "*"
  # stackoverflow = "*"
  # serverfault = "*"

  # Gaming
  # steam = "*"
  # mobygames = "*"

  # Music
  # lastfm = "*"
  # discogs = "*"

  # Other
  # keybase = "*"
